{{- $root := . -}}
{{- range $id, $val := .Values.configMaps -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
{{- if .name }}
  name: {{ .name | quote }}
{{- else }}
  name: {{ include "util.v1.autoname" $root }}-cm-{{ $id }}
{{- end }}
  namespace: {{ $root.Release.Namespace }}
  labels:
{{ include "standard-app.v1.resource-labels" $root | indent 4 }}
data:
{{- range $dataID, $dataVal := .data }}
  {{ $dataID }}: {{ $dataVal | default "" | quote }}
{{- else }}
  {}
{{- end}}
{{- end }}
