{{ if .Values.ingress.enabled }}
{{- $defaultServiceName := include "standard-app.v1.default-service-name" . -}}
{{- $serviceName := default $defaultServiceName .Values.service.name -}}
{{- $servicePort := .Values.service.port -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "util.v1.autoname" . }}-http
  namespace: {{ .Values.Namespace }}
  labels:
{{ include "standard-app.v1.resource-labels" . | indent 4 }}
  annotations:
    {{- if .Values.ingress.auth }}
    alb.ingress.kubernetes.io/auth-type: oidc
    alb.ingress.kubernetes.io/auth-idp-oidc: '{"issuer":"https://55places.okta.com","authorizationEndpoint":"https://55places.okta.com/oauth2/v1/authorize","tokenEndpoint":"https://55places.okta.com/oauth2/v1/token","userInfoEndpoint":"https://55places.okta.com/oauth2/v1/userinfo","secretName": "{{ include "util.v1.autoname" . }}-okta-oidc" }'
    alb.ingress.kubernetes.io/auth-scope: 'openid profile'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "Redirectconfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    {{- end }}
{{ with .Values.ingress.extraAnnotations }}{{ toYaml . | indent 4 }}{{ end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
{{- if .Values.ingress.defaultBackend.enabled }}
  - pathType: {{ .Values.ingress.pathType | default "Prefix" | quote }}
    backend:
      service:
        name: {{ $serviceName | quote }}
        port:
          number: {{ $servicePort }}
{{- end }}
  rules:
  - host: {{ required ".Values.ingress.host must be specified when .Values.ingress.enabled is true" .Values.ingress.host | quote }}
    http:
      paths:
      {{- if .Values.ingress.auth }}
      - path: /
        pathType: {{ .Values.ingress.pathType | default "Prefix" | quote }}
        backend:
          service:
            name: ssl-redirect
            port:
             name: use-annotation
      {{- end }}
      - path: {{ .Values.ingress.path | default "/" | quote }}
        pathType: {{ .Values.ingress.pathType | default "Prefix" | quote }}
        backend:
          service:
            name: {{ $serviceName | quote }}
            port:
              number: {{ $servicePort }}
{{- range .Values.ingress.extraHosts }}
  - host: {{ . | quote }}
    http:
      paths:
      - path: /
        pathType: {{ .Values.ingress.pathType | default "Prefix" | quote }}
      {{- if .Values.ingress.auth }}
      - backend:
          service:
            name: ssl-redirect
            port:
              name: use-annotation
      {{- end }}
      - path: /
        pathType: {{ .Values.ingress.pathType | default "Prefix" | quote }}
      - backend:
          service:
            name: {{ $serviceName | quote }}
            port:
              number: {{ $servicePort }}
{{- end }}
{{ if .Values.ingress.auth }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "util.v1.autoname" . }}-okta-oidc
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "standard-app.v1.resource-labels" . | indent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  clientId:  {{ .Values.ingress.oidc.clientId | default "" | b64enc | quote }}
  clientSecret:  {{ .Values.ingress.oidc.clientSecret  | default "" | b64enc | quote }}
{{ end }}
{{ end }}
