{{- if .Values.http.pdb.enabled -}}
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "util.v1.autoname" . }}-http
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "standard-app.v1.resource-labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
{{ include "standard-app.v1.selector-labels" . | indent 6 }}
      tier: http
{{- with .Values.http.pdb.maxUnavailable }}
  maxUnavailable: {{ . }}
{{- end }}
{{- with .Values.http.pdb.minAvailable }}
  minAvailable: {{ . }}
{{- end }}
{{- end -}}
