{{ if and .Values.http.enabled .Values.nginx.enabled }}
{{- $root := . }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "standard-app.v1.default-nginx-configmap-name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "standard-app.v1.resource-labels" . | indent 4 }}
data:
{{ range $name, $contents := .Values.nginx.confTemplates }}
{{- if or (hasKey $root.Values.nginx.confTemplatesEnabled $name | not) (index $root.Values.nginx.confTemplatesEnabled $name) }}
  {{ $name }}: {{ $contents | default "" | quote }}
{{- end }}
{{ else }}
  empty.conf: ""
{{ end }}
{{ end }}
