{{- if and .Values.http.enabled .Values.nginx.basicAuth .Values.nginx.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "standard-app.v1.default-nginx-auth-configmap-name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "standard-app.v1.resource-labels" . | indent 4 }}
data:
  htpasswd.txt: |
{{- range $username, $password := .Values.nginx.basicAuth }}
    {{ $username }}:{PLAIN}{{ $password }}
{{- end }}
{{- end }}
