{{ if .Values.service.enabled }}
{{- $defaultName := include "standard-app.v1.default-service-name" . -}}
{{- $metrics := .Values.service.metrics -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ default $defaultName .Values.service.name | quote }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "standard-app.v1.resource-labels" . | indent 4 }}
{{- if $metrics.enabled }}
    prometheus.io/scrape: "true"
{{ end -}}
{{ if .Values.service.extraAnnotations }}
  annotations:
{{ toYaml .Values.service.extraAnnotations | indent 4 }}
{{ end }}
spec:
  type: {{ .Values.service.type  | quote }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
{{ if $metrics.enabled }}
  - name: {{ $metrics.name }}
    port: {{ $metrics.port }}
    targetPort: {{ $metrics.targetPort }}
{{ end }}
  selector:
{{ include "standard-app.v1.selector-labels" . | indent 4 }}
    tier: http
{{ end }}
